language: node_js
node_js: stable
dist: trusty
# S: Build Lifecycle
install:
  - npm install
before_install:
  - git submodule update --init --remote --recursive
#before_script:
# - npm install -g gulp
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "meiminjun"
  - git config user.email "251222845@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GitHub_TOKEN_BLOG}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/meiminjun/meiminjun.github.io
